// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: ../../tests/corpus\interactive\stateful_counter.dart
// JET version: test-golden
// Generated at: 2026-09-15T22:18:38.653750

import 'package:jaspr/jaspr.dart';

@client
class CounterWidget extends StatefulComponent {
  const CounterWidget({super.key});

  @override
  State<CounterWidget> createState() => _CounterWidgetState();
}

class _CounterWidgetState extends State<CounterWidget> {
  // TODO(jet): migrate StatefulWidget state fields here

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield div([]);
  }
}
