name: jet_workspace
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/jet_annotations
  - packages/jet_builder
  - packages/jet_cli
  - packages/jet_mcp
  - tests/jet_builder_test
dev_dependencies:
  husky: ^0.1.7
