import 'package:test/test.dart';

import 'package:jet_builder/src/emitter/jaspr_emitter.dart';
import 'package:jet_builder/src/parser/flutter_ast_parser.dart';
import 'package:jet_builder/src/visitor/style_accumulator_visitor.dart';
import 'package:jet_builder/src/visitor/widget_node.dart';

void main() {
  late FlutterAstParser parser;
  late JasprEmitter emitter;

  setUp(() {
    parser = const FlutterAstParser();
    emitter = const JasprEmitter();
  });

  // ─────────────────────────────────────────────────────────────────────────────
  // Helpers
  // ─────────────────────────────────────────────────────────────────────────────

  /// Parses [source], visits it, emits Jaspr source and returns the raw string.
  String emit(String source) {
    final result = parser.parse(source: source, path: 'lib/ui/test.dart');
    expect(result.isUsable, isTrue,
        reason: 'Parse failed: ${result.failureMessage}');
    final visitor = StyleAccumulatorVisitor();
    result.unit!.accept(visitor);
    expect(visitor.components, isNotEmpty,
        reason: 'No components found in source');
    return emitter.emitFile(
      components: visitor.components,
      sourceFile: 'lib/ui/test.dart',
    );
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // File-level output
  // ─────────────────────────────────────────────────────────────────────────────

  group('File output', () {
    test('Contains required Jaspr import', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) => Text('Hi');
}
''');
      expect(output, contains("import 'package:jaspr/jaspr.dart'"));
    });

    test('Contains GENERATED BY JET header comment', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) => Text('Hi');
}
''');
      expect(output, contains('GENERATED BY JET'));
      expect(output, contains('DO NOT EDIT MANUALLY'));
    });
  });

  // ─────────────────────────────────────────────────────────────────────────────
  // StatelessComponent emission
  // ─────────────────────────────────────────────────────────────────────────────

  group('StatelessComponent', () {
    test('StatelessWidget → StatelessComponent class', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class HeroSection extends StatelessWidget {
  @override Widget build(BuildContext context) => Column(children: []);
}
''');
      expect(output, contains('class HeroSection extends StatelessComponent'));
      expect(output, isNot(contains('@client')));
    });

    test('build() method uses sync* and Iterable<Component>', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) => Column(children: []);
}
''');
      expect(output,
          contains('Iterable<Component> build(BuildContext context) sync*'));
    });

    test('build() uses yield for root node', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) => Column(children: []);
}
''');
      expect(output, contains('yield'));
    });
  });

  // ─────────────────────────────────────────────────────────────────────────────
  // @client StatefulComponent emission
  // ─────────────────────────────────────────────────────────────────────────────

  group('@client StatefulComponent', () {
    test('StatefulWidget → @client annotation before class', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Counter extends StatefulWidget {
  @override State<Counter> createState() => _CounterState();
}
class _CounterState extends State<Counter> {
  @override Widget build(BuildContext context) => Text('count');
}
''');
      expect(output, contains('@client'));
      expect(output, contains('class Counter extends StatefulComponent'));
    });

    test('Interactive child (ElevatedButton) promotes to @client', () {
      final output = emit('''
import 'package:flutter/material.dart';
class LoginForm extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return ElevatedButton(onPressed: () {}, child: Text('Login'));
  }
}
''');
      expect(output, contains('@client'));
    });

    test('State class is emitted with TODO comment', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Counter extends StatefulWidget {
  @override State<Counter> createState() => _CounterState();
}
class _CounterState extends State<Counter> {
  @override Widget build(BuildContext context) => Text('count');
}
''');
      expect(output,
          contains('TODO(jet): migrate StatefulWidget state fields here'));
    });
  });

  // ─────────────────────────────────────────────────────────────────────────────
  // HTML tag emission
  // ─────────────────────────────────────────────────────────────────────────────

  group('HTML tag emission', () {
    test('Column → div() with flex flex-col classes', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) => Column(children: []);
}
''');
      expect(output, contains('div('));
      expect(output, contains('flex-col'));
    });

    test('Scaffold → main()', () {
      final output = emit('''
import 'package:flutter/material.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) => Scaffold(body: Column(children: []));
}
''');
      expect(output, contains('main('));
    });

    test('AppBar → header()', () {
      final output = emit('''
import 'package:flutter/material.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('My App')),
      body: Column(children: []),
    );
  }
}
''');
      expect(output, contains('header('));
    });

    test('AppBar title Text is promoted to h1()', () {
      final output = emit('''
import 'package:flutter/material.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('My App')),
      body: Column(children: []),
    );
  }
}
''');
      expect(output, contains('h1('));
    });

    test('Text → p() with text content', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) => Text('Hello World');
}
''');
      expect(output, contains("p("));
      expect(output, contains("text('Hello World')"));
    });

    test('ElevatedButton → button()', () {
      final output = emit('''
import 'package:flutter/material.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return ElevatedButton(onPressed: () {}, child: Text('Go'));
  }
}
''');
      expect(output, contains('button('));
    });

    test('ListView → ul()', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return ListView(children: [Text('Item')]);
  }
}
''');
      expect(output, contains('ul('));
    });

    test('Image.network → img() with src', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return Image.network('https://example.com/photo.jpg');
  }
}
''');
      expect(output, contains('img('));
      expect(output, contains('https://example.com/photo.jpg'));
    });
  });

  // ─────────────────────────────────────────────────────────────────────────────
  // Padding → CSS class on child
  // ─────────────────────────────────────────────────────────────────────────────

  group('Modifier accumulation in output', () {
    test('Padding(all:16) → p-4 class on child div', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(16),
      child: Column(children: []),
    );
  }
}
''');
      expect(output, contains('p-4'));
      expect(output, contains('flex-col'));
    });

    test('Center → flex items-center justify-center on child', () {
      final output = emit('''
import 'package:flutter/widgets.dart';
class Demo extends StatelessWidget {
  @override Widget build(BuildContext context) {
    return Center(child: Column(children: []));
  }
}
''');
      expect(output, contains('items-center'));
      expect(output, contains('justify-center'));
    });
  });

  // ─────────────────────────────────────────────────────────────────────────────
  // @JetRoute metadata in output
  // ─────────────────────────────────────────────────────────────────────────────

  group('@JetRoute metadata in output', () {
    test('Emits route path and title as comments', () {
      // Inline the JetRoute class so parser does not need the package
      final output = emit('''
import 'package:flutter/widgets.dart';
class JetRoute {
  final String path;
  final String title;
  const JetRoute({required this.path, required this.title});
}
@JetRoute(path: '/about', title: 'About Us')
class AboutScreen extends StatelessWidget {
  @override Widget build(BuildContext context) => Column(children: []);
}
''');
      expect(output, contains('// JET: Route /about'));
      expect(output, contains('title: About Us'));
    });
  });

  // ─────────────────────────────────────────────────────────────────────────────
  // UnknownNode → TODO comment
  // ─────────────────────────────────────────────────────────────────────────────

  group('UnknownNode handling', () {
    test('emitNode for UnknownNode produces TODO comment', () {
      const emitter = JasprEmitter();
      const node = UnknownNode(originalWidgetName: 'CustomPainter');
      // Direct test of the component method
      final component = ComponentNode(
        name: 'Demo',
        isStateful: false,
        buildBody: node,
      );
      final output = emitter.emitComponent(component);
      expect(output, contains('TODO(jet): manual port — CustomPainter'));
    });
  });
}
