import '../visitor/widget_node.dart';

/// Converts a [ComponentNode] IR tree into a Jaspr Dart source string.
///
/// This is the final stage of the JET transpilation pipeline.
///
/// ## Output format
/// - [StatelessWidget] → `StatelessComponent` with a `build()` method returning `Iterable<Component>`.
/// - [StatefulWidget] → `@client StatefulComponent` with full `State` mapping.
/// - [StructuralNode] → Jaspr HTML function calls (`div(...)`, `h1(...)`, etc.)
/// - [UnknownNode] → `// TODO(jet): manual port — {WidgetName}` comment.
///
/// ## Usage
/// ```dart
/// final emitter = JasprEmitter();
/// final source = emitter.emitFile(
///   components: visitor.components,
///   sourceFile: 'lib/ui/home_screen.dart',
///   version: '0.1.0-dev',
/// );
/// ```
class JasprEmitter {
  const JasprEmitter();

  static const _fileHeader = '''
// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: {sourceFile}
// JET version: {version}
// Generated at: {timestamp}

import 'package:jaspr/jaspr.dart';
''';

  /// Generates a complete `.jaspr.dart` file for the given [components].
  String emitFile({
    required List<ComponentNode> components,
    required String sourceFile,
    String version = '0.1.0-dev',
  }) {
    final buffer = StringBuffer();

    buffer.writeln(_fileHeader
        .replaceAll('{sourceFile}', sourceFile)
        .replaceAll('{version}', version)
        .replaceAll('{timestamp}', DateTime.now().toIso8601String()));

    for (final component in components) {
      buffer.writeln(emitComponent(component));
      buffer.writeln();
    }

    return buffer.toString();
  }

  /// Emits a single Jaspr component class from a [ComponentNode].
  String emitComponent(ComponentNode component) {
    final buffer = StringBuffer();

    // @JetRoute metadata comment block
    if (component.routeMetadata != null) {
      final meta = component.routeMetadata!;
      buffer.writeln('// JET: Route ${meta.path} | title: ${meta.title}');
      if (meta.description != null) {
        buffer.writeln('// JET: meta description: ${meta.description}');
      }
    }

    if (component.isStateful) {
      buffer.write(_emitStatefulComponent(component));
    } else {
      buffer.write(_emitStatelessComponent(component));
    }

    return buffer.toString();
  }

  // ───────────────────────────────────────────────────────────────────────────
  // StatelessComponent
  // ───────────────────────────────────────────────────────────────────────────

  String _emitStatelessComponent(ComponentNode component) {
    final buffer = StringBuffer();
    buffer.writeln('class ${component.name} extends StatelessComponent {');
    buffer.writeln('  const ${component.name}({super.key});');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  Iterable<Component> build(BuildContext context) sync* {');

    if (component.buildBody != null) {
      final body = _emitNode(component.buildBody!, indent: 4);
      buffer.writeln('    yield $body;');
    } else {
      buffer.writeln('    yield div([], []);');
    }

    buffer.writeln('  }');
    buffer.writeln('}');
    return buffer.toString();
  }

  // ───────────────────────────────────────────────────────────────────────────
  // @client StatefulComponent (Islands)
  // ───────────────────────────────────────────────────────────────────────────

  String _emitStatefulComponent(ComponentNode component) {
    final buffer = StringBuffer();
    buffer.writeln('@client');
    buffer.writeln('class ${component.name} extends StatefulComponent {');
    buffer.writeln('  const ${component.name}({super.key});');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln(
        '  State<${component.name}> createState() => _${component.name}State();');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln(
        'class _${component.name}State extends State<${component.name}> {');
    buffer.writeln('  // TODO(jet): migrate StatefulWidget state fields here');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  Iterable<Component> build(BuildContext context) sync* {');

    if (component.buildBody != null) {
      final body = _emitNode(component.buildBody!, indent: 4);
      buffer.writeln('    yield $body;');
    } else {
      buffer.writeln('    yield div([], []);');
    }

    buffer.writeln('  }');
    buffer.writeln('}');
    return buffer.toString();
  }

  // ───────────────────────────────────────────────────────────────────────────
  // Node Emission
  // ───────────────────────────────────────────────────────────────────────────

  /// Recursively emits a [WidgetNode] as a Jaspr function call string.
  String _emitNode(WidgetNode node, {int indent = 0}) {
    return switch (node) {
      StructuralNode() => _emitStructural(node, indent: indent),
      ComponentNode() => '${node.name}()',
      UnknownNode(:final originalWidgetName) =>
        '// TODO(jet): manual port — $originalWidgetName',
      ModifierNode() =>
        '// TODO(jet): orphaned modifier — ${node.tailwindClasses.join(' ')}',
    };
  }

  String _emitStructural(StructuralNode node, {int indent = 0}) {
    final tag = node.htmlTag;
    final classes = node.allClasses.where((c) => c.isNotEmpty).join(' ');
    final hasText = node.textContent != null && node.textContent!.isNotEmpty;
    final hasChildren = node.children.isNotEmpty;

    // Self-closing elements (no children)
    if (tag == 'hr' || tag == 'img' || tag == 'input') {
      final attrStr = _emitAttributes(node.attributes, classes);
      return '$tag($attrStr, [])';
    }

    // Build the classes argument
    final classesArg = classes.isNotEmpty ? "classes: '$classes'" : '';

    // Build attributes
    final attrParts = <String>[];
    if (classesArg.isNotEmpty) attrParts.add(classesArg);
    for (final entry in node.attributes.entries) {
      if (entry.key != 'class') {
        attrParts.add("${_attrToParam(entry.key)}: '${entry.value}'");
      }
    }

    // Build children
    if (!hasChildren && !hasText) {
      return '$tag([${attrParts.join(', ')}], [])';
    }

    final pad = ' ' * (indent + 2);
    final closePad = ' ' * indent;

    final childrenParts = <String>[];

    if (hasText) {
      final escapedText =
          node.textContent!.replaceAll("'", "\\'").replaceAll('\n', '\\n');
      childrenParts.add("${pad}text('$escapedText')");
    }

    for (final child in node.children) {
      final childStr = _emitNode(child, indent: indent + 2);
      childrenParts.add('$pad$childStr');
    }

    final childrenStr = childrenParts.join(',\n');
    final attrsStr = attrParts.isNotEmpty ? '[${attrParts.join(', ')}]' : '[]';

    return '$tag($attrsStr, [\n$childrenStr,\n$closePad])';
  }

  String _emitAttributes(Map<String, String> attributes, String classes) {
    final parts = <String>[];
    if (classes.isNotEmpty) parts.add("classes: '$classes'");
    for (final entry in attributes.entries) {
      parts.add("${_attrToParam(entry.key)}: '${entry.value}'");
    }
    return parts.join(', ');
  }

  /// Converts HTML attribute names to Jaspr named parameter names.
  String _attrToParam(String attrName) => switch (attrName) {
        'src' => 'src',
        'alt' => 'alt',
        'href' => 'href',
        'type' => 'type',
        'id' => 'id',
        'role' => 'role',
        'aria-label' => 'ariaLabel',
        'aria-describedby' => 'ariaDescribedBy',
        _ => attrName.replaceAllMapped(
            RegExp(r'-([a-z])'),
            (m) => m.group(1)!.toUpperCase(),
          ),
      };
}
