// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: ../../tests/corpus\text\text_headline.dart
// JET version: test-golden
// Generated at: 2026-09-12T20:38:42.575669

import 'package:jaspr/jaspr.dart';

class TextHeadlineDemo extends StatelessComponent {
  const TextHeadlineDemo({super.key});

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield div(classes: 'flex flex-col items-start', [
      h1(classes: 'text-4xl font-bold', [
        text('Page Title'),
      ]),
      h2(classes: 'text-2xl', [
        text('Section Heading'),
      ]),
      h3(classes: 'text-lg', [
        text('Subsection'),
      ]),
      p([], [
        text('Regular paragraph text goes here.'),
      ]),
    ]);
  }
}
