// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: ../../tests/corpus\input\textfield_basic.dart
// JET version: test-golden
// Generated at: 2026-09-12T20:38:41.927649

import 'package:jaspr/jaspr.dart';

@client
class TextFieldDemo extends StatefulComponent {
  const TextFieldDemo({super.key});

  @override
  State<TextFieldDemo> createState() => _TextFieldDemoState();
}

class _TextFieldDemoState extends State<TextFieldDemo> {
  // TODO(jet): migrate StatefulWidget state fields here

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield div(classes: 'p-4 flex flex-col', [
      input(classes: 'border rounded px-3 py-2 w-full', type: 'text', []),
      div([], []),
      button(
          classes:
              'h-4 bg-blue-600 text-white rounded px-4 py-2 hover:bg-blue-700',
          [
            p([], [
              text('Submit'),
            ]),
          ]),
    ]);
  }
}
