// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: ../../tests/corpus\layout\column_basic.dart
// JET version: test-golden
// Generated at: 2026-09-15T22:18:38.688821

import 'package:jaspr/jaspr.dart';

class ColumnBasicDemo extends StatelessComponent {
  const ColumnBasicDemo({super.key});

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield div(classes: 'p-4 flex flex-col justify-start', [
      p([text('Hello World')]),
      p([text('From Flutter')]),
    ]);
  }
}
