// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: ../../tests/corpus/layout/listview_basic.dart
// JET version: test-golden
// Generated at: 2026-09-16T23:37:25.158815

import 'package:jaspr/jaspr.dart';

class ListViewDemo extends StatelessComponent {
  const ListViewDemo({super.key});

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield ul(classes: 'flex flex-col overflow-y-auto', [
      li([
        p(classes: 'p-2', [text('Item One')]),
      ]),
      li([
        p(classes: 'p-2', [text('Item Two')]),
      ]),
      li([
        p(classes: 'p-2', [text('Item Three')]),
      ]),
    ]);
  }
}
