// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: ../../tests/corpus/layout/scaffold_appbar.dart
// JET version: test-golden
// Generated at: 2026-09-16T03:01:44.264831

import 'package:jaspr/jaspr.dart';

// JET: Route /home | title: Home — My App
// JET: meta description: Welcome to the home page.
class HomeScreen extends StatelessComponent {
  const HomeScreen({super.key});

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield main(classes: 'min-h-screen flex flex-col', [
      header(classes: 'flex items-center px-4 py-2 bg-white shadow', [
        h1(classes: 'text-xl font-semibold', [text('Home')]),
      ]),
      div(
        classes:
            'flex items-center justify-center flex flex-col justify-center',
        [
          p([text('Welcome!')]),
          p([text('Build for web and mobile.')]),
        ],
      ),
    ]);
  }
}
