// GENERATED BY JET — DO NOT EDIT MANUALLY
// ignore_for_file: type=lint
// Source: ../../tests/corpus/navigation/poison_import_test.dart
// JET version: test-golden
// Generated at: 2026-09-15T22:18:38.942408

import 'package:jaspr/jaspr.dart';

@client
class PoisonedScreen extends StatefulComponent {
  const PoisonedScreen({super.key});

  @override
  State<PoisonedScreen> createState() => _PoisonedScreenState();
}

class _PoisonedScreenState extends State<PoisonedScreen> {
  // TODO(jet): migrate StatefulWidget state fields here

  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield div(classes: 'flex flex-col', [
      p([text('Poisoned')]),
      button(
        classes: 'bg-blue-600 text-white rounded px-4 py-2 hover:bg-blue-700',
        [
          p([text('Go to next')]),
        ],
      ),
    ]);
  }
}
